
# All hosts in the NCI framework should use this.

class nci {

	# This should be done by the rc.local (userdata) script
	# (which is in turn generated by the nova-boot wrapper),
	# but there's no harm in making sure things stay sane.
	file { '/puppet':
		ensure => link,
		target => "/etc/puppet",
	}
	file { '/puppet/private':
		mode => 0700,
		owner => root,
		group => root,
	}

	# Convenience script to update puppet, since it's nearly
	# but not quite as simple as "cd /puppet && git pull &&
	# puppet apply".
	include bash
	file { '/usr/local/sbin/puppet-update':
		ensure => present,
		source => "puppet:///modules/nci/puppet-update",
		mode => 0700,
		owner => 'root',
		group => 'root',
	}

	file { '/opt/bin':
		ensure => directory,
		owner => root,
		group => root,
		mode => 0755,
	}

	include python-novaclient

	# Fix RHEL brain damage, where /etc/profile.d/* is erroneously
	# sourced by /etc/bashrc.
	include fix-etc-bashrc

}
